version: '3'
services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  frontend:
    build: ./frontend
    image: t-web-frontend
    restart: always
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
