version: '3'
services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "${SERVER_PORT:-4000}:${SERVER_PORT:-4000}"

  frontend:
    build: ./frontend
    image: t-web-frontend
    restart: always
    ports:
      - "${FRONT_PORT:-4200}:80"
