version: '3.6'
services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - "80:80"

  mongo:
    image: mongo
    volumes:
      - ./db_data:/data/db
    expose:
      - "27017"

volumes:
  db_data:
