version: '3.6'
services:
  backend:
    build: ./backend
    restart: always
    expose:
      - 80
    links:
      - mongo
    environment:
      - SERVER_PORT=80
      - VIRTUAL_HOST=${BACKEND_DOMAIN}
      - LETSENCRYPT_HOST=${BACKEND_DOMAIN}
      - FRONTEND_URL=https://${FRONTEND_DOMAIN}
      - MONGO_URL=mongodb://mongo:27017/cryptocodex

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    expose:
      - 80
    restart: always
    environment:
      - VIRTUAL_HOST=${FRONTEND_DOMAIN}
      - LETSENCRYPT_HOST=${FRONTEND_DOMAIN}

  mongo:
    image: mongo
    volumes:
      - ./db_data:/data/db
    expose:
      - "27017"

volumes:
  db_data:

networks:
  default:
    external:
      name: ${PRIVATE_NETWORK}
