version: '3'
services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "4200:3000"
    links:
      - mongo

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "4000:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
