version: '3'
services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - "80:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
