version: '3.6'
services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "4200:4200"

  mongo:
    image: mongo
    volumes:
      - db_data:/data/db
    expose:
      - "27017"

volumes:
  db_data:
