version: '3'
services:
  backend:
    container_name: t-web-backend
    build: ./backend
    restart: always
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=35.214.83.191
      - VIRTUAL_PORT=3000

  frontend:
    build: ./frontend
    image: t-web-frontend
    restart: always
    depends_on:
      - backend
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=35.214.83.191

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
